name: barigazaofficial
description: "barigazaofficial"
publish_to: 'none'
version: 1.0.3+8

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  geolocator: ^13.0.2
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  mime: ^2.0.0
  firebase_core: ^3.10.0
  firebase_app_check: ^0.3.2
  firebase_storage: ^12.4.0
  firebase_crashlytics: ^4.3.0
  firebase_analytics: ^11.4.0
  geocoding: ^3.0.0
  http: ^1.1.0
  cached_network_image: ^3.4.1
  flutter_naver_map: ^1.3.0+1
  path_provider: ^2.1.5
  flutter_svg: ^2.0.9
  share_plus: ^10.1.4
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  google_mobile_ads: ^5.3.1
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff" # 배경색 지정
  adaptive_icon_foreground: "assets/images/icon.png"
  remove_alpha_ios: true
